version: "3.2"
services:
  composer:
    image: "composer:latest"
    volumes:
      - "./:/var/www/app"
    working_dir: /var/www/app
    command: install

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - "./private/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./public:/var/www/app/public"
    depends_on:
      - php
      - db
    links:
      - php
      - db

  php:
    image: php:7.1-fpm-alpine
    restart: always
    volumes:
       - "./private/docker/php/php.ini:/usr/local/etc/php/php.ini"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp

  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp

